Repository xamarin/Essentials, pull requests merged in 2018-04, with the labels that each got.

#146 GH-145 Adjust Package References for Android
  Caboodle/Caboodle.csproj
  Caboodle/Vibration/Vibration.android.cs
Labels: awaiting review

#144 GH-143 Change compass to event based.
  Caboodle.Tests/Compass_Tests.cs
  Caboodle/Compass/Compass.android.cs
  Caboodle/Compass/Compass.ios.cs
  Caboodle/Compass/Compass.netstandard.cs
  Caboodle/Compass/Compass.shared.cs
  Caboodle/Compass/Compass.uwp.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Compass_Tests.cs
  Samples/Caboodle.Samples/ViewModel/CompassViewModel.cs
  docs/en/Microsoft.Caboodle/Compass.xml
  docs/en/Microsoft.Caboodle/CompassChangedEventArgs.xml
  docs/en/Microsoft.Caboodle/CompassChangedEventHandler.xml
  docs/en/index.xml
Labels: awaiting review

#124 [Proposal] Add an API to Track App Versions
  Caboodle/VersionTracking/VersionTracking.shared.cs
  README.md
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  docs/en/Microsoft.Caboodle/VersionTracking.xml
  docs/en/index.xml
Labels: DO-NOT-MERGE, awaiting review

#158 Update private preferences for version tracking & secure
  Samples/Samples/View/BrowserPage.xaml
  Xamarin.Essentials/Preferences/Preferences.shared.cs
  Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs
  Xamarin.Essentials/VersionTracking/VersionTracking.shared.cs
Labels: awaiting review

#164 Updating docs to work around mdoc bug
  Xamarin.Essentials/mdoc.targets
  docs/en/FrameworksIndex/Xamarin.Essentials.Android.xml
  docs/en/FrameworksIndex/Xamarin.Essentials.UWP.xml
  docs/en/FrameworksIndex/Xamarin.Essentials.iOS.xml
  docs/en/FrameworksIndex/Xamarin.Essentials.xml
  docs/en/Xamarin.Essentials/Browser.xml
  docs/en/Xamarin.Essentials/PermissionException.xml
  docs/frameworks.xml
Labels: awaiting review

#163 GH-133: Remove the ConfigureAwait(false)
  Xamarin.Essentials/SecureStorage/SecureStorage.uwp.cs
Labels: awaiting review

#165 GH-137 API Cleanup
  Xamarin.Essentials/Accelerometer/Accelerometer.ios.cs
  Xamarin.Essentials/Battery/Battery.android.cs
  Xamarin.Essentials/Battery/Battery.shared.cs
  Xamarin.Essentials/Battery/Battery.uwp.cs
  Xamarin.Essentials/Clipboard/Clipboard.android.cs
  Xamarin.Essentials/Compass/Compass.ios.cs
  Xamarin.Essentials/Compass/Compass.netstandard.cs
  Xamarin.Essentials/Connectivity/Connectivity.android.cs
  Xamarin.Essentials/Connectivity/Connectivity.ios.cs
  Xamarin.Essentials/Connectivity/Connectivity.netstandard.cs
  Xamarin.Essentials/Connectivity/Connectivity.shared.cs
  Xamarin.Essentials/Connectivity/Connectivity.shared.enums.cs
  Xamarin.Essentials/Connectivity/Connectivity.uwp.cs
  Xamarin.Essentials/DataTransfer/DataTransfer.android.cs
  Xamarin.Essentials/DataTransfer/DataTransfer.ios.cs
  Xamarin.Essentials/DataTransfer/DataTransfer.netstandard.cs
  Xamarin.Essentials/DataTransfer/DataTransfer.shared.cs
  Xamarin.Essentials/DataTransfer/DataTransfer.uwp.cs
  Xamarin.Essentials/Flashlight/Flashlight.android.cs
  Xamarin.Essentials/Geocoding/Geocoding.uwp.cs
  Xamarin.Essentials/Gyroscope/Gyroscope.ios.cs
  Xamarin.Essentials/Gyroscope/Gyroscope.uwp.cs
  Xamarin.Essentials/Magnetometer/Magnetometer.ios.cs
  Xamarin.Essentials/Permissions/Permissions.ios.cs
  Xamarin.Essentials/Permissions/Permissions.netstandard.cs
  Xamarin.Essentials/Permissions/Permissions.shared.enums.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.shared.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.uwp.cs
  Xamarin.Essentials/Preferences/Preferences.netstandard.cs
  Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
  Xamarin.Essentials/SecureStorage/SecureStorage.uwp.cs
  Xamarin.Essentials/Sms/Sms.android.cs
  Xamarin.Essentials/Types/Location.shared.cs
  Xamarin.Essentials/Types/LocationExtensions.shared.cs
  Xamarin.Essentials/Types/Placemark.shared.cs
  Xamarin.Essentials/Types/PlacemarkExtensions.shared.cs
  Xamarin.Essentials/Vibration/Vibration.android.cs
  Xamarin.Essentials/Vibration/Vibration.ios.cs
  Xamarin.Essentials/Vibration/Vibration.uwp.cs
Labels: awaiting review

#132 GH-7: Geolocation API's
  DeviceTests/DeviceTests.Android/Properties/AndroidManifest.xml
  DeviceTests/DeviceTests.Android/Properties/AssemblyInfo.cs
  DeviceTests/DeviceTests.Shared/DeviceTests.Shared.projitems
  DeviceTests/DeviceTests.Shared/Geolocation_Tests.cs
  DeviceTests/DeviceTests.Shared/Permissions_Tests.cs
  DeviceTests/DeviceTests.iOS/Info.plist
  Samples/Samples.Android/Properties/AndroidManifest.xml
  Samples/Samples.Android/Properties/AssemblyInfo.cs
  Samples/Samples.UWP/Package.appxmanifest
  Samples/Samples.iOS/Info.plist
  Samples/Samples/View/GeolocationPage.xaml
  Samples/Samples/View/GeolocationPage.xaml.cs
  Samples/Samples/ViewModel/GeolocationViewModel.cs
  Samples/Samples/ViewModel/HomeViewModel.cs
  Xamarin.Essentials/Geolocation/Geolocation.android.cs
  Xamarin.Essentials/Geolocation/Geolocation.ios.cs
  Xamarin.Essentials/Geolocation/Geolocation.netstandard.cs
  Xamarin.Essentials/Geolocation/Geolocation.shared.cs
  Xamarin.Essentials/Geolocation/Geolocation.uwp.cs
  Xamarin.Essentials/Geolocation/GeolocationRequest.ios.cs
  Xamarin.Essentials/Geolocation/GeolocationRequest.shared.cs
  Xamarin.Essentials/Geolocation/GeolocationRequest.uwp.cs
  Xamarin.Essentials/Permissions/Permissions.ios.cs
  Xamarin.Essentials/Platform/Platform.android.cs
  Xamarin.Essentials/SecureStorage/SecureStorage.uwp.cs
  Xamarin.Essentials/Types/Location.shared.cs
  Xamarin.Essentials/Types/LocationExtensions.android.cs
  Xamarin.Essentials/Types/LocationExtensions.ios.cs
  Xamarin.Essentials/Types/LocationExtensions.uwp.cs
  Xamarin.Essentials/Types/Shared/Utils.shared.cs
  docs/en/Xamarin.Essentials/AccelerometerChangedEventArgs.xml
  docs/en/Xamarin.Essentials/Geolocation.xml
  docs/en/Xamarin.Essentials/GeolocationAccuracy.xml
  docs/en/Xamarin.Essentials/GeolocationRequest.xml
  docs/en/Xamarin.Essentials/Location.xml
  docs/en/index.xml
Labels: DO-NOT-MERGE

#180 GH-134: Cleaned up the API a bit:
  DeviceTests/DeviceTests.Shared/Accelerometer_Tests.cs
  DeviceTests/DeviceTests.Shared/Battery_Tests.cs
  DeviceTests/DeviceTests.Shared/Compass_Tests.cs
  DeviceTests/DeviceTests.Shared/DeviceTests.Shared.projitems
  DeviceTests/DeviceTests.Shared/Email_Tests.cs
  DeviceTests/DeviceTests.Shared/Flashlight_Tests.cs
  DeviceTests/DeviceTests.Shared/Geolocation_Tests.cs
  DeviceTests/DeviceTests.Shared/Gyroscope_Tests.cs
  DeviceTests/DeviceTests.Shared/HardwareSupport.cs
  DeviceTests/DeviceTests.Shared/Magnetometer_Tests.cs
  DeviceTests/DeviceTests.Shared/SecureStorage_Tests.cs
  DeviceTests/DeviceTests.Shared/Traits.cs
  DeviceTests/DeviceTests.Shared/Utils.cs
  Xamarin.Essentials/Accelerometer/Accelerometer.android.cs
  Xamarin.Essentials/Accelerometer/Accelerometer.ios.cs
  Xamarin.Essentials/Accelerometer/Accelerometer.netstandard.cs
  Xamarin.Essentials/Accelerometer/Accelerometer.shared.cs
  Xamarin.Essentials/Accelerometer/Accelerometer.uwp.cs
  Xamarin.Essentials/Battery/Battery.android.cs
  Xamarin.Essentials/Battery/Battery.shared.cs
  Xamarin.Essentials/Battery/Battery.uwp.cs
  Xamarin.Essentials/Browser/Browser.android.cs
  Xamarin.Essentials/Browser/Browser.ios.cs
  Xamarin.Essentials/Browser/Browser.uwp.cs
  Xamarin.Essentials/Compass/Compass.android.cs
  Xamarin.Essentials/Compass/Compass.ios.cs
  Xamarin.Essentials/Compass/Compass.shared.cs
  Xamarin.Essentials/Compass/Compass.uwp.cs
  Xamarin.Essentials/Connectivity/Connectivity.android.cs
  Xamarin.Essentials/Connectivity/Connectivity.shared.cs
  Xamarin.Essentials/Connectivity/Connectivity.uwp.cs
  Xamarin.Essentials/Email/Email.netstandard.cs
  Xamarin.Essentials/Gyroscope/Gyroscope.android.cs
  Xamarin.Essentials/Gyroscope/Gyroscope.ios.cs
  Xamarin.Essentials/Gyroscope/Gyroscope.shared.cs
  Xamarin.Essentials/Gyroscope/Gyroscope.uwp.cs
  Xamarin.Essentials/Magnetometer/Magnetometer.android.cs
  Xamarin.Essentials/Magnetometer/Magnetometer.ios.cs
  Xamarin.Essentials/Magnetometer/Magnetometer.shared.cs
  Xamarin.Essentials/Magnetometer/Magnetometer.uwp.cs
  Xamarin.Essentials/Permissions/Permissions.android.cs
  Xamarin.Essentials/Permissions/Permissions.ios.cs
  Xamarin.Essentials/Permissions/Permissions.uwp.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.ios.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.netstandard.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.shared.cs
  Xamarin.Essentials/Platform/Platform.android.cs
  Xamarin.Essentials/Platform/Platform.uwp.cs
  Xamarin.Essentials/ScreenLock/ScreenLock.ios.cs
  Xamarin.Essentials/Sms/Sms.netstandard.cs
  Xamarin.Essentials/Types/Shared/Exceptions.shared.cs
  Xamarin.Essentials/Vibration/Vibration.netstandard.cs
Labels: awaiting review

#184 GH-179: Refactored the iOS Reachability
  Xamarin.Essentials/Connectivity/Connectivity.ios.cs
  Xamarin.Essentials/Connectivity/Connectivity.ios.reachability.cs
Labels: awaiting review

#210 GH-208,207,206,204 Multiple Fixes to sample application
  Samples/Samples.Android/Properties/AndroidManifest.xml
  Samples/Samples/ViewModel/AccelerometerViewModel.cs
  Samples/Samples/ViewModel/BaseViewModel.cs
  Samples/Samples/ViewModel/CompassViewModel.cs
  Samples/Samples/ViewModel/GeolocationViewModel.cs
  Samples/Samples/ViewModel/GyroscopeViewModel.cs
  Samples/Samples/ViewModel/HomeViewModel.cs
  Samples/Samples/ViewModel/MagnetometerViewModel.cs
  Samples/Samples/ViewModel/PhoneDialerViewModel.cs
  Samples/Samples/ViewModel/SecureStorageViewModel.cs
  Samples/Samples/ViewModel/SmsViewModel.cs
  Xamarin.Essentials/AppInfo/AppInfo.android.cs
  Xamarin.Essentials/Battery/Battery.android.cs
  Xamarin.Essentials/Browser/Browser.android.cs
  Xamarin.Essentials/Connectivity/Connectivity.android.cs
  Xamarin.Essentials/DataTransfer/DataTransfer.android.cs
  Xamarin.Essentials/DeviceDisplay/DeviceDisplay.android.cs
  Xamarin.Essentials/DeviceInfo/DeviceInfo.android.cs
  Xamarin.Essentials/Email/Email.android.cs
  Xamarin.Essentials/FileSystem/FileSystem.android.cs
  Xamarin.Essentials/Geocoding/Geocoding.android.cs
  Xamarin.Essentials/Geolocation/Geolocation.android.cs
  Xamarin.Essentials/Permissions/Permissions.android.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.android.cs
  Xamarin.Essentials/Platform/Platform.android.cs
  Xamarin.Essentials/SecureStorage/SecureStorage.android.cs
  Xamarin.Essentials/SecureStorage/SecureStorage.shared.cs
  Xamarin.Essentials/Sms/Sms.android.cs
Labels: awaiting review

#213 GH-205: Fix for flashlight toggling off when permission was prompted.
  Samples/Samples/ViewModel/FlashlightViewModel.cs
  Xamarin.Essentials/Flashlight/Flashlight.android.cs
Labels: awaiting review

#217 GH-168 Update sample error messages
  Samples/Samples/ViewModel/AccelerometerViewModel.cs
  Samples/Samples/ViewModel/CompassViewModel.cs
  Samples/Samples/ViewModel/FlashlightViewModel.cs
  Samples/Samples/ViewModel/GeocodingViewModel.cs
  Samples/Samples/ViewModel/GyroscopeViewModel.cs
  Samples/Samples/ViewModel/MagnetometerViewModel.cs
  Samples/Samples/ViewModel/PhoneDialerViewModel.cs
  Samples/Samples/ViewModel/SmsViewModel.cs
  Samples/Samples/ViewModel/VibrationViewModel.cs
Labels: awaiting review
