Repository xamarin/Essentials, pull requests merged in 2018-12, with the labels that each got.

#637 Use SharedPreferences.Editor.Apply to perform disk writes asynchronously
  Xamarin.Essentials/Preferences/Preferences.android.cs
Labels: awaiting review

#650 GH-649: Return distinct connectivity profiles.
  DeviceTests/DeviceTests.Shared/Connectivity_Tests.cs
  Xamarin.Essentials/Connectivity/Connectivity.shared.cs
Labels: awaiting review

#657 GH-656: Connectivity Updates on Android for Not Available
  Xamarin.Essentials/Connectivity/Connectivity.android.cs
Labels: awaiting review

#659 [docs] Update global metadata for API docs
  docs/en/docfx.json
Labels: DO-NOT-MERGE

#665 Allow for code reuse on macOS
  Xamarin.Essentials/Geolocation/Geolocation.ios.cs
Labels: awaiting review, azdo-sync
