Repository xamarin/Essentials, pull requests merged in 2018-03, with the labels that each got.

#43 Fixing line endings and added .gitattributes to make sure it stays fixed
  .gitattributes
  Caboodle.sln
  Caboodle/Caboodle.csproj
  Caboodle/Platform/Platform.android.cs
  Caboodle/Platform/Platform.ios.cs
  Caboodle/Platform/Platform.netstandard.cs
  Caboodle/Platform/Platform.shared.cs
  Caboodle/Platform/Platform.uwp.cs
  Caboodle/Preferences/Preferences.android.cs
  Caboodle/Preferences/Preferences.ios.cs
  Caboodle/Preferences/Preferences.netstandard.cs
  Caboodle/Preferences/Preferences.shared.cs
  Caboodle/Preferences/Preferences.uwp.cs
  Caboodle/Preferences/PreferencesExtensions.shared.cs
  Caboodle/Shared/Exceptions.shared.cs
  DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj
  DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs
  DeviceTests/Caboodle.DeviceTests.Android/Properties/AssemblyInfo.cs
  DeviceTests/Caboodle.DeviceTests.Android/Resources/Resource.designer.cs
  DeviceTests/Caboodle.DeviceTests.Android/Resources/layout/Main.axml
  DeviceTests/Caboodle.DeviceTests.Android/Resources/layout/Tabbar.axml
  DeviceTests/Caboodle.DeviceTests.Android/Resources/layout/Toolbar.axml
  DeviceTests/Caboodle.DeviceTests.Android/Resources/values/Strings.xml
  DeviceTests/Caboodle.DeviceTests.Android/Resources/values/styles.xml
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.shproj
  DeviceTests/Caboodle.DeviceTests.Shared/Preferences_Tests.cs
  DeviceTests/Caboodle.DeviceTests.UWP/App.xaml
  DeviceTests/Caboodle.DeviceTests.UWP/App.xaml.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  DeviceTests/Caboodle.DeviceTests.UWP/Package.appxmanifest
  DeviceTests/Caboodle.DeviceTests.UWP/Properties/AssemblyInfo.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Properties/Default.rd.xml
  DeviceTests/Caboodle.DeviceTests.iOS/AppDelegate.cs
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
  DeviceTests/Caboodle.DeviceTests.iOS/Entitlements.plist
  DeviceTests/Caboodle.DeviceTests.iOS/Info.plist
  DeviceTests/Caboodle.DeviceTests.iOS/Main.cs
  DeviceTests/Caboodle.DeviceTests.iOS/Properties/AssemblyInfo.cs
  DeviceTests/Caboodle.DeviceTests.iOS/Resources/LaunchScreen.storyboard
Labels: enhancement

#29 Implementation of Geocoding #28
  .editorconfig
  Caboodle.Tests/Geocoding_Tests.cs
  Caboodle/Caboodle.csproj
  Caboodle/Geocoding/Geocoding.android.cs
  Caboodle/Geocoding/Geocoding.ios.cs
  Caboodle/Geocoding/Geocoding.netstandard.cs
  Caboodle/Geocoding/Geocoding.shared.cs
  Caboodle/Geocoding/Geocoding.uwp.cs
  Caboodle/Types/Location.shared.cs
  Caboodle/Types/LocationExtensions.android.cs
  Caboodle/Types/LocationExtensions.ios.cs
  Caboodle/Types/LocationExtensions.shared.cs
  Caboodle/Types/LocationExtensions.uwp.cs
  Caboodle/Types/Placemark.shared.cs
  Caboodle/Types/PlacemarkExtensions.android.cs
  Caboodle/Types/PlacemarkExtensions.ios.cs
  Caboodle/Types/PlacemarkExtensions.shared.cs
  Caboodle/Types/PlacemarkExtensions.uwp.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/Geocoding_Tests.cs
  Samples/Caboodle.Samples/App.xaml.cs
  Samples/Caboodle.Samples/Caboodle.Samples.csproj
  Samples/Caboodle.Samples/View/GeocodingPage.xaml
  Samples/Caboodle.Samples/View/GeocodingPage.xaml.cs
  Samples/Caboodle.Samples/View/PreferencesPage.xaml
  Samples/Caboodle.Samples/ViewModel/GeocodingViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/PreferencesViewModel.cs
Labels: enhancement

#44 Platform should be static as we will never instantiate it.
  Caboodle/Platform/Platform.android.cs
  Caboodle/Platform/Platform.ios.cs
  Caboodle/Platform/Platform.netstandard.cs
  Caboodle/Platform/Platform.shared.cs
  Caboodle/Platform/Platform.uwp.cs
Labels: awaiting review

#47 Fix the styles for StyleCop
  Caboodle.Tests/Geocoding_Tests.cs
  Caboodle.Tests/Preferences_Tests.cs
  Caboodle/Geocoding/Geocoding.android.cs
  Caboodle/Geocoding/Geocoding.ios.cs
  Caboodle/Geocoding/Geocoding.netstandard.cs
  Caboodle/Geocoding/Geocoding.uwp.cs
  Caboodle/Platform/Platform.android.cs
  Caboodle/Preferences/Preferences.ios.cs
  Caboodle/Preferences/Preferences.shared.cs
  Caboodle/Preferences/Preferences.uwp.cs
  Caboodle/Shared/Exceptions.shared.cs
  Caboodle/Types/Location.shared.cs
  Caboodle/Types/LocationExtensions.android.cs
  Caboodle/Types/LocationExtensions.ios.cs
  Caboodle/Types/LocationExtensions.shared.cs
  Caboodle/Types/Placemark.shared.cs
  Caboodle/Types/PlacemarkExtensions.android.cs
  Caboodle/Types/PlacemarkExtensions.ios.cs
  Caboodle/Types/PlacemarkExtensions.shared.cs
  DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs
  DeviceTests/Caboodle.DeviceTests.Android/Properties/AssemblyInfo.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Geocoding_Tests.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Preferences_Tests.cs
  DeviceTests/Caboodle.DeviceTests.UWP/App.xaml.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Properties/AssemblyInfo.cs
  DeviceTests/Caboodle.DeviceTests.iOS/AppDelegate.cs
  DeviceTests/Caboodle.DeviceTests.iOS/Properties/AssemblyInfo.cs
  Samples/Caboodle.Samples.Android/Properties/AssemblyInfo.cs
  Samples/Caboodle.Samples.UWP/App.xaml.cs
  Samples/Caboodle.Samples.UWP/Properties/AssemblyInfo.cs
  Samples/Caboodle.Samples.iOS/Properties/AssemblyInfo.cs
  Samples/Caboodle.Samples/App.xaml.cs
  Samples/Caboodle.Samples/View/GeocodingPage.xaml.cs
  Samples/Caboodle.Samples/View/HomePage.xaml.cs
  Samples/Caboodle.Samples/View/PreferencesPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/GeocodingViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/PreferencesViewModel.cs
Labels: awaiting review

#21 Initial attempt at contribution, submission docs, and templates
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  SUBMITTING-ISSUES.md
Labels: DO-NOT-MERGE

#34 Added the StyleCop.Analyzers NuGet to enforce styles
  .editorconfig
  Caboodle.Tests/Caboodle.Tests.csproj
  Caboodle.ruleset
  Caboodle.sln
  Caboodle/Caboodle.csproj
  CodeStyles.targets
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP_TemporaryKey.pfx
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
  DeviceTests/Caboodle.DeviceTests.iOS/GlobalSuppressions.cs
  Samples/Caboodle.Samples.Android/Caboodle.Samples.Android.csproj
  Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP.csproj
  Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP_TemporaryKey.pfx
  Samples/Caboodle.Samples.iOS/Caboodle.Samples.iOS.csproj
  Samples/Caboodle.Samples.iOS/GlobalSuppressions.cs
  Samples/Caboodle.Samples/Caboodle.Samples.csproj
  stylecop.json
Labels: DO-NOT-MERGE

#49 Battery Implementation
  Caboodle.Tests/Battery_Tests.cs
  Caboodle.Tests/Geocoding_Tests.cs
  Caboodle/Battery/Battery.android.cs
  Caboodle/Battery/Battery.ios.cs
  Caboodle/Battery/Battery.netstandard.cs
  Caboodle/Battery/Battery.shared.cs
  Caboodle/Battery/Battery.uwp.cs
  Caboodle/Platform/Platform.android.cs
  Caboodle/Platform/Platform.ios.cs
  Caboodle/Platform/Platform.netstandard.cs
  Caboodle/Platform/Platform.uwp.cs
  Caboodle/Platform/PlatformExtensions.uwp.cs
  Caboodle/Preferences/PreferencesExtensions.shared.cs
  Caboodle/Shared/Exceptions.shared.cs
  DeviceTests/Caboodle.DeviceTests.Android/Properties/AndroidManifest.xml
  DeviceTests/Caboodle.DeviceTests.Shared/Battery_Tests.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  Samples/Caboodle.Samples.Android/Properties/AndroidManifest.xml
  Samples/Caboodle.Samples/Caboodle.Samples.csproj
  Samples/Caboodle.Samples/View/BatteryPage.xaml
  Samples/Caboodle.Samples/View/BatteryPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/BatteryViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
Labels: awaiting review, enhancement

#62 Update forms and remove mvvmhelpers
  DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
  Samples/Caboodle.Samples.Android/Caboodle.Samples.Android.csproj
  Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP.csproj
  Samples/Caboodle.Samples.iOS/Caboodle.Samples.iOS.csproj
  Samples/Caboodle.Samples/Caboodle.Samples.csproj
  Samples/Caboodle.Samples/ViewModel/BaseViewModel.cs
  Samples/Caboodle.Samples/ViewModel/BatteryViewModel.cs
  Samples/Caboodle.Samples/ViewModel/GeocodingViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/PreferencesViewModel.cs
Labels: awaiting review, enhancement

#60 Update README.md
  README.md
Labels: awaiting review, enhancement

#78 CI changes for api docs
  docs/packages.docs.config
Labels: DO-NOT-MERGE

#72 GH-73: Added docs for Preferences
  docs/en/Microsoft.Caboodle/Preferences.xml
Labels: DO-NOT-MERGE

#42 GH-14: Add FileSystem
  Caboodle.Tests/FileSystem_Tests.cs
  Caboodle/FileSystem/FileSystem.android.cs
  Caboodle/FileSystem/FileSystem.ios.cs
  Caboodle/FileSystem/FileSystem.netstandard.cs
  Caboodle/FileSystem/FileSystem.shared.cs
  Caboodle/FileSystem/FileSystem.uwp.cs
  DeviceTests/Caboodle.DeviceTests.Android/Assets/AppBundleFile.txt
  DeviceTests/Caboodle.DeviceTests.Android/Assets/AppBundleFile_NoExtension
  DeviceTests/Caboodle.DeviceTests.Android/Assets/Folder/AppBundleFile_Nested.txt
  DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/FileSystem_Tests.cs
  DeviceTests/Caboodle.DeviceTests.UWP/AppBundleFile.txt
  DeviceTests/Caboodle.DeviceTests.UWP/AppBundleFile_NoExtension
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  DeviceTests/Caboodle.DeviceTests.UWP/Folder/AppBundleFile_Nested.txt
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
  DeviceTests/Caboodle.DeviceTests.iOS/Resources/AppBundleFile.txt
  DeviceTests/Caboodle.DeviceTests.iOS/Resources/AppBundleFile_NoExtension
  DeviceTests/Caboodle.DeviceTests.iOS/Resources/Folder/AppBundleFile_Nested.txt
  Samples/Caboodle.Samples.Android/Assets/FileSystemTemplate.txt
  Samples/Caboodle.Samples.Android/Caboodle.Samples.Android.csproj
  Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP.csproj
  Samples/Caboodle.Samples.UWP/FileSystemTemplate.txt
  Samples/Caboodle.Samples.iOS/Caboodle.Samples.iOS.csproj
  Samples/Caboodle.Samples.iOS/Resources/FileSystemTemplate.txt
  Samples/Caboodle.Samples/Caboodle.Samples.csproj
  Samples/Caboodle.Samples/View/FileSystemPage.xaml
  Samples/Caboodle.Samples/View/FileSystemPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/FileSystemViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  docs/en/Microsoft.Caboodle/FileSystem.xml
  docs/en/index.xml
Labels: awaiting review, enhancement

#89 GH-88 Fix for UWP battery when fully charged
  Caboodle/Battery/Battery.uwp.cs
Labels: awaiting review

#93 Update contributing based on feedback.
  README.md
Labels: awaiting review

#91 GH-26: Add SMS API
  Caboodle.Tests/Sms_Tests.cs
  Caboodle/Platform/Platform.android.cs
  Caboodle/Platform/Platform.ios.cs
  Caboodle/Shared/Exceptions.shared.cs
  Caboodle/Sms/Sms.android.cs
  Caboodle/Sms/Sms.ios.cs
  Caboodle/Sms/Sms.netstandard.cs
  Caboodle/Sms/Sms.shared.cs
  Caboodle/Sms/Sms.uwp.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/Sms_Tests.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Utils.cs
  Samples/Caboodle.Samples/App.xaml
  Samples/Caboodle.Samples/Converters/NegativeConverter.cs
  Samples/Caboodle.Samples/View/BasePage.cs
  Samples/Caboodle.Samples/View/SMSPage.xaml
  Samples/Caboodle.Samples/View/SMSPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/BaseViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/SmsViewModel.cs
  docs/en/Microsoft.Caboodle/Sms.xml
  docs/en/Microsoft.Caboodle/SmsMessage.xml
  docs/en/index.xml
Labels: awaiting review, enhancement

#96 Update and finalize documentation.
  .gitignore
  Caboodle.sln
  Caboodle/NamespaceSummaries.xml
  Caboodle/Sms/Sms.android.cs
  DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj
  DeviceTests/Caboodle.DeviceTests.Android/Resources/Resource.designer.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
  Samples/Caboodle.Samples.Android/Resources/Resource.designer.cs
  docs/en/Microsoft.Caboodle/BatteryChangedEventArgs.xml
  docs/en/Microsoft.Caboodle/BatteryChangedEventHandler.xml
  docs/en/Microsoft.Caboodle/Clipboard.xml
  docs/en/Microsoft.Caboodle/DeviceInfo+Idioms.xml
  docs/en/Microsoft.Caboodle/DeviceInfo+Platforms.xml
  docs/en/Microsoft.Caboodle/DeviceInfo.xml
  docs/en/Microsoft.Caboodle/DeviceType.xml
  docs/en/Microsoft.Caboodle/DistanceUnits.xml
  docs/en/Microsoft.Caboodle/FeatureNotSupportedException.xml
  docs/en/Microsoft.Caboodle/FileSystem.xml
  docs/en/Microsoft.Caboodle/Geocoding.xml
  docs/en/Microsoft.Caboodle/NotImplementedInReferenceAssemblyException.xml
  docs/en/Microsoft.Caboodle/NotImplentedInReferenceAssembly.xml
  docs/en/Microsoft.Caboodle/PermissionException.xml
  docs/en/Microsoft.Caboodle/Platform.xml
  docs/en/Microsoft.Caboodle/Preferences.xml
  docs/en/Microsoft.Caboodle/ScreenMetrics.xml
  docs/en/Microsoft.Caboodle/ScreenMetricsChanagedEventArgs.xml
  docs/en/Microsoft.Caboodle/ScreenMetricsChanagedEventHandler.xml
  docs/en/Microsoft.Caboodle/ScreenOrientation.xml
  docs/en/Microsoft.Caboodle/ScreenRotation.xml
  docs/en/Microsoft.Caboodle/Sms.xml
  docs/en/index.xml
  docs/en/ns-Microsoft.Caboodle.xml
Labels: awaiting review

#97 GH-22: Initial Support for Data Transfer aka Share
  Caboodle.Tests/DataTransfer_Tests.cs
  Caboodle/DataTransfer/DataTransfer.android.cs
  Caboodle/DataTransfer/DataTransfer.ios.cs
  Caboodle/DataTransfer/DataTransfer.netstandard.cs
  Caboodle/DataTransfer/DataTransfer.shared.cs
  Caboodle/DataTransfer/DataTransfer.uwp.cs
  Samples/Caboodle.Samples.Android/Caboodle.Samples.Android.csproj
  Samples/Caboodle.Samples/Caboodle.Samples.csproj
  Samples/Caboodle.Samples/View/DataTransferPage.xaml
  Samples/Caboodle.Samples/View/DataTransferPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/DataTransferViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  docs/en/Microsoft.Caboodle/DataTransfer.xml
  docs/en/Microsoft.Caboodle/ShareTextRequest.xml
Labels: awaiting review, enhancement

#101 Add ScreenLock API
  Caboodle/ScreenLock/ScreenLock.android.cs
  Caboodle/ScreenLock/ScreenLock.ios.cs
  Caboodle/ScreenLock/ScreenLock.netstandard.cs
  Caboodle/ScreenLock/ScreenLock.shared.cs
  Caboodle/ScreenLock/ScreenLock.uwp.cs
  DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/ScreenLock_Tests.cs
  Samples/Caboodle.Samples/View/ScreenLockPage.xaml
  Samples/Caboodle.Samples/View/ScreenLockPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/ScreenLockViewModel.cs
Labels: awaiting review, enhancement

#68 GH-13: Browser API
  .gitignore
  Caboodle.Tests/Browser_Tests.cs
  Caboodle/Browser/Browser.android.cs
  Caboodle/Browser/Browser.ios.cs
  Caboodle/Browser/Browser.netstandard.cs
  Caboodle/Browser/Browser.shared.cs
  Caboodle/Browser/Browser.uwp.cs
  Caboodle/Caboodle.csproj
  DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj
  Samples/Caboodle.Samples.Android/Caboodle.Samples.Android.csproj
  Samples/Caboodle.Samples/View/BrowserPage.xaml
  Samples/Caboodle.Samples/View/BrowserPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/BrowserViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  docs/en/Microsoft.Caboodle/Browser.xml
  docs/en/Microsoft.Caboodle/BrowserLaunchType.xml
Labels: awaiting review, enhancement

#37 GH-25: Add PhoneDialer API
  Caboodle.Tests/PhoneDialer_Tests.cs
  Caboodle/Caboodle.csproj
  Caboodle/PhoneDialer/PhoneDialer.android.cs
  Caboodle/PhoneDialer/PhoneDialer.ios.cs
  Caboodle/PhoneDialer/PhoneDialer.netstandard.cs
  Caboodle/PhoneDialer/PhoneDialer.uwp.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/PhoneDialer_Tests.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP.csproj
  Samples/Caboodle.Samples/View/PhoneDialerPage.xaml
  Samples/Caboodle.Samples/View/PhoneDialerPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/PhoneDialerViewModel.cs
Labels: DO-NOT-MERGE

#109 GH-25: Add PhoneDialer API
  Caboodle.Tests/PhoneDialer_Tests.cs
  Caboodle/Caboodle.csproj
  Caboodle/PhoneDialer/PhoneDialer.android.cs
  Caboodle/PhoneDialer/PhoneDialer.ios.cs
  Caboodle/PhoneDialer/PhoneDialer.netstandard.cs
  Caboodle/PhoneDialer/PhoneDialer.shared.cs
  Caboodle/PhoneDialer/PhoneDialer.uwp.cs
  Caboodle/Platform/Platform.android.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/PhoneDialer_Tests.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  Samples/Caboodle.Samples.UWP/Caboodle.Samples.UWP.csproj
  Samples/Caboodle.Samples/View/PhoneDialerPage.xaml
  Samples/Caboodle.Samples/View/PhoneDialerPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/PhoneDialerViewModel.cs
  docs/en/Microsoft.Caboodle/PhoneDialer.xml
  docs/en/index.xml
Labels: awaiting review, enhancement

#114 GH-113 Fix Sms to user proper API. Tested on device. Updated api level helpers
  Caboodle/PhoneDialer/PhoneDialer.android.cs
  Caboodle/Platform/Platform.android.cs
  Caboodle/Sms/Sms.android.cs
Labels: awaiting review

#6 GH-8: Add Connectivity API
  Caboodle.Tests/Connectivity_Tests.cs
  Caboodle/Caboodle.csproj
  Caboodle/Clipboard/Clipboard.android.cs
  Caboodle/Connectivity/Connectivity.android.cs
  Caboodle/Connectivity/Connectivity.ios.cs
  Caboodle/Connectivity/Connectivity.ios.reachability.cs
  Caboodle/Connectivity/Connectivity.netstandard.cs
  Caboodle/Connectivity/Connectivity.shared.cs
  Caboodle/Connectivity/Connectivity.shared.enums.cs
  Caboodle/Connectivity/Connectivity.uwp.cs
  Caboodle/Platform/Platform.android.cs
  DeviceTests/Caboodle.DeviceTests.Android/Properties/AndroidManifest.xml
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/Connectivity_Tests.cs
  Samples/Caboodle.Samples.Android/Properties/AndroidManifest.xml
  Samples/Caboodle.Samples/View/ConnectivityPage.xaml
  Samples/Caboodle.Samples/View/ConnectivityPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/ConnectivityViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  docs/en/Microsoft.Caboodle/ConnectionProfile.xml
  docs/en/Microsoft.Caboodle/Connectivity.xml
  docs/en/Microsoft.Caboodle/ConnectivityChangedEventArgs.xml
  docs/en/Microsoft.Caboodle/ConnectivityChangedEventHandler.xml
  docs/en/Microsoft.Caboodle/NetworkAccess.xml
Labels: awaiting review, enhancement

#115 Fix Browser Sample Picker
  Samples/Caboodle.Samples/ViewModel/BrowserViewModel.cs
Labels: awaiting review

#102 GH-66: SecureStorage Implementation
  Caboodle.Tests/SecureStorage_Tests.cs
  Caboodle.ruleset
  Caboodle/AssemblyInfo.shared.cs
  Caboodle/SecureStorage/SecureStorage.android.cs
  Caboodle/SecureStorage/SecureStorage.ios.cs
  Caboodle/SecureStorage/SecureStorage.netstandard.cs
  Caboodle/SecureStorage/SecureStorage.shared.cs
  Caboodle/SecureStorage/SecureStorage.uwp.cs
  Caboodle/Shared/Utils.shared.cs
  Caboodle/Types/Shared/Exceptions.shared.cs
  Caboodle/Types/Shared/Utils.shared.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/SecureStorage_Tests.cs
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
  Samples/Caboodle.Samples/View/SecureStoragePage.cs
  Samples/Caboodle.Samples/View/SecureStoragePage.xaml
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  Samples/Caboodle.Samples/ViewModel/SecureStorageViewModel.cs
  docs/en/Microsoft.Caboodle/SecureStorage.xml
  docs/en/index.xml
Labels: enhancement

#117 GH-18: Permissions Internal implementation
  Caboodle/Battery/Battery.android.cs
  Caboodle/Caboodle.csproj
  Caboodle/Connectivity/Connectivity.android.cs
  Caboodle/Permissions/PermissionEnums.shared.cs
  Caboodle/Permissions/Permissions.android.cs
  Caboodle/Permissions/Permissions.ios.cs
  Caboodle/Permissions/Permissions.netstandard.cs
  Caboodle/Permissions/Permissions.shared.cs
  Caboodle/Permissions/Permissions.uwp.cs
  Caboodle/Platform/Platform.android.cs
  Caboodle/Platform/Platform.ios.cs
  Caboodle/Types/Shared/Exceptions.shared.cs
  DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/Permissions_Tests.cs
  README.md
  Samples/Caboodle.Samples.Android/MainActivity.cs
Labels: awaiting review

#116 GH-48 Add initial compass API
  Caboodle.Tests/Compass_Tests.cs
  Caboodle.sln
  Caboodle/Compass/Compass.android.cs
  Caboodle/Compass/Compass.ios.cs
  Caboodle/Compass/Compass.netstandard.cs
  Caboodle/Compass/Compass.shared.cs
  Caboodle/Compass/Compass.uwp.cs
  Caboodle/Platform/Platform.android.cs
  Caboodle/Types/SensorSpeed.shared.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Caboodle.DeviceTests.Shared.projitems
  DeviceTests/Caboodle.DeviceTests.Shared/Compass_Tests.cs
  README.md
  Samples/Caboodle.Samples/View/BatteryPage.xaml
  Samples/Caboodle.Samples/View/CompassPage.xaml
  Samples/Caboodle.Samples/View/CompassPage.xaml.cs
  Samples/Caboodle.Samples/ViewModel/CompassViewModel.cs
  Samples/Caboodle.Samples/ViewModel/HomeViewModel.cs
  docs/en/Microsoft.Caboodle/Compass.xml
  docs/en/Microsoft.Caboodle/CompassData.xml
  docs/en/Microsoft.Caboodle/SensorSpeed.xml
  docs/en/index.xml
Labels: awaiting review, enhancement

#128 DeviceTests: Added Traits to headless runner
  DeviceTests/Caboodle.DeviceTests.Android/Caboodle.DeviceTests.Android.csproj
  DeviceTests/Caboodle.DeviceTests.Android/MainActivity.cs
  DeviceTests/Caboodle.DeviceTests.Shared/Traits.cs
  DeviceTests/Caboodle.DeviceTests.UWP/App.xaml.cs
  DeviceTests/Caboodle.DeviceTests.UWP/Caboodle.DeviceTests.UWP.csproj
  DeviceTests/Caboodle.DeviceTests.iOS/AppDelegate.cs
  DeviceTests/Caboodle.DeviceTests.iOS/Caboodle.DeviceTests.iOS.csproj
Labels: awaiting review
