Repository xamarin/Essentials, pull requests merged in 2019-12, with the labels that each got.

#927 [WIP] GH-923 Implement AppTheme for iOS/tvOS/Android/UWP (Need Tizen Still)
  DeviceTests/DeviceTests.Shared/DeviceInfo_Tests.cs
  Samples/Samples/View/AppInfoPage.xaml
  Samples/Samples/ViewModel/AppInfoViewModel.cs
  Xamarin.Essentials/AppInfo/AppInfo.android.cs
  Xamarin.Essentials/AppInfo/AppInfo.ios.tvos.watchos.cs
  Xamarin.Essentials/AppInfo/AppInfo.netstandard.cs
  Xamarin.Essentials/AppInfo/AppInfo.shared.cs
  Xamarin.Essentials/AppInfo/AppInfo.tizen.cs
  Xamarin.Essentials/AppInfo/AppInfo.uwp.cs
  Xamarin.Essentials/AppInfo/AppTheme.shared.cs
  docs/en/FrameworksIndex/xamarin-essentials-android.xml
  docs/en/FrameworksIndex/xamarin-essentials-ios.xml
  docs/en/FrameworksIndex/xamarin-essentials-tvos.xml
  docs/en/FrameworksIndex/xamarin-essentials-uwp.xml
  docs/en/FrameworksIndex/xamarin-essentials-watchos.xml
  docs/en/FrameworksIndex/xamarin-essentials.xml
  docs/en/Xamarin.Essentials/AppInfo.xml
  docs/en/Xamarin.Essentials/AppTheme.xml
  docs/en/index.xml
Labels: awaiting-review, hacktoberfest 🎃

#720 GH-969 Clipboard Changed
  Samples/Samples/View/ClipboardPage.xaml
  Samples/Samples/ViewModel/ClipboardViewModel.cs
  Xamarin.Essentials/Clipboard/Clipboard.android.cs
  Xamarin.Essentials/Clipboard/Clipboard.ios.cs
  Xamarin.Essentials/Clipboard/Clipboard.netstandard.tvos.watchos.tizen.cs
  Xamarin.Essentials/Clipboard/Clipboard.shared.cs
  Xamarin.Essentials/Clipboard/Clipboard.uwp.cs
  docs/en/FrameworksIndex/xamarin-essentials-android.xml
  docs/en/FrameworksIndex/xamarin-essentials-ios.xml
  docs/en/FrameworksIndex/xamarin-essentials-uwp.xml
  docs/en/FrameworksIndex/xamarin-essentials.xml
  docs/en/Xamarin.Essentials/Clipboard.xml
Labels: ready-to-merge

#949 Permissions API
  DeviceTests/DeviceTests.Shared/Geolocation_Tests.cs
  DeviceTests/DeviceTests.Shared/Permissions_Tests.cs
  Samples/Samples.iOS/Info.plist
  Samples/Samples/Model/PermissionItem.cs
  Samples/Samples/View/PermissionsPage.xaml
  Samples/Samples/View/PermissionsPage.xaml.cs
  Samples/Samples/ViewModel/HomeViewModel.cs
  Samples/Samples/ViewModel/PermissionsViewModel.cs
  Tests/Tests.csproj
  Xamarin.Essentials/AppInfo/AppInfo.tizen.cs
  Xamarin.Essentials/Battery/Battery.android.cs
  Xamarin.Essentials/Browser/Browser.tizen.cs
  Xamarin.Essentials/Connectivity/Connectivity.android.cs
  Xamarin.Essentials/Connectivity/Connectivity.tizen.cs
  Xamarin.Essentials/Email/Email.tizen.cs
  Xamarin.Essentials/Flashlight/Flashlight.android.cs
  Xamarin.Essentials/Flashlight/Flashlight.tizen.cs
  Xamarin.Essentials/Geocoding/Geocoding.tizen.cs
  Xamarin.Essentials/Geolocation/Geolocation.android.cs
  Xamarin.Essentials/Geolocation/Geolocation.ios.cs
  Xamarin.Essentials/Geolocation/Geolocation.tizen.cs
  Xamarin.Essentials/Geolocation/Geolocation.uwp.cs
  Xamarin.Essentials/Launcher/Launcher.tizen.cs
  Xamarin.Essentials/Map/Map.tizen.cs
  Xamarin.Essentials/Permissions/Permissions.android.cs
  Xamarin.Essentials/Permissions/Permissions.ios.cs
  Xamarin.Essentials/Permissions/Permissions.ios.tvos.cs
  Xamarin.Essentials/Permissions/Permissions.ios.tvos.watchos.cs
  Xamarin.Essentials/Permissions/Permissions.ios.watchos.cs
  Xamarin.Essentials/Permissions/Permissions.netstandard.cs
  Xamarin.Essentials/Permissions/Permissions.netstandard.tvos.watchos.cs
  Xamarin.Essentials/Permissions/Permissions.shared.cs
  Xamarin.Essentials/Permissions/Permissions.shared.enums.cs
  Xamarin.Essentials/Permissions/Permissions.tizen.cs
  Xamarin.Essentials/Permissions/Permissions.uwp.cs
  Xamarin.Essentials/PhoneDialer/PhoneDialer.tizen.cs
  Xamarin.Essentials/Preferences/Preferences.android.cs
  Xamarin.Essentials/Share/Share.tizen.cs
  Xamarin.Essentials/Sms/Sms.tizen.cs
  Xamarin.Essentials/Types/FileProvider.android.cs
  Xamarin.Essentials/Types/Shared/Utils.shared.cs
  Xamarin.Essentials/Vibration/Vibration.android.cs
  Xamarin.Essentials/Vibration/Vibration.tizen.cs
  Xamarin.Essentials/Xamarin.Essentials.csproj
Labels: hacktoberfest 🎃
